# Generated by Django 2.2.24 on 2022-03-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=50)),
                ('vacancy', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
