# Generated by Django 2.2.24 on 2022-03-17 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hostels',
            new_name='Hostel',
        ),
    ]
