# Generated by Django 2.2.24 on 2022-03-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20220317_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='image',
            field=models.CharField(default='SOME STRING', max_length=2083),
        ),
    ]
